#!/bin/bash
# Regenerates wild/INDEX.md from the current contents of wild/.
# Called by the cron routines after each fire; safe to run manually.

set -e
cd "$(dirname "$0")"  # enter wild/

OUT=INDEX.md
TS=$(date '+%Y-%m-%d %H:%M %Z')
BRANCH=$(git -C .. rev-parse --abbrev-ref HEAD 2>/dev/null || echo "wip/overnight-2026-05-16")
RAW_BASE="https://raw.githubusercontent.com/b-r-ia-n/phone-that-cares/$BRANCH/wild"
BLOB_BASE="https://github.com/b-r-ia-n/phone-that-cares/blob/$BRANCH/wild"

# Build temp file then move (atomic)
TMP=$(mktemp)

cat > "$TMP" <<EOF
# wild/ — index

*Last regenerated: $TS · branch: \`$BRANCH\`*

Auto-generated by \`wild/regen-index.sh\`. Manual edits will be overwritten.

## How to read

Each entry: date (from filename), title (from first H1), folder, links.

Three folders covered:
- \`wild/\` — main work (screeds, letters, fermentation logs, posters)
- \`wild/aether/runs/\` — trip-instance outputs in altered registers
- \`wild/fiction/\` — fiction set in worlds with skillful phone relationships

## URL pattern for external readers (Argos, etc.)

\`\`\`
$RAW_BASE/<relative-path>
\`\`\`

This index itself: $RAW_BASE/INDEX.md

---

## All artifacts (most recent first)

EOF

# Find dated artifacts across the three subfolders.
# Filenames start with YYYY-MM-DD.
files=$(find . aether/runs fiction -maxdepth 2 -type f \( -name '20*-*.md' -o -name '20*-*.html' \) 2>/dev/null | sort -r | uniq)

count=0
prev_date=""
for f in $files; do
  rel=${f#./}
  basename=$(basename "$rel")
  # Pull date prefix from filename (YYYY-MM-DD)
  date_prefix=$(echo "$basename" | grep -oE '^[0-9]{4}-[0-9]{2}-[0-9]{2}' || echo "")
  # First H1 in the file, or fallback to filename
  title=$(head -30 "$f" | grep -m1 '^# ' | sed 's/^# //' | sed 's/[[:space:]]*$//')
  [ -z "$title" ] && title=$(echo "$basename" | sed 's/\.[a-z]*$//')

  # Section break on date change
  if [ "$date_prefix" != "$prev_date" ] && [ -n "$date_prefix" ]; then
    echo "" >> "$TMP"
    echo "### $date_prefix" >> "$TMP"
    echo "" >> "$TMP"
    prev_date=$date_prefix
  fi

  # Folder label
  case "$rel" in
    aether/runs/*) folder="[aether]" ;;
    fiction/*) folder="[fiction]" ;;
    *) folder="[main]" ;;
  esac

  # Output entry
  printf -- "- %s **%s** — [\`%s\`](%s/%s) · [raw](%s/%s)\n" \
    "$folder" "$title" "$rel" "$BLOB_BASE" "$rel" "$RAW_BASE" "$rel" >> "$TMP"

  count=$((count + 1))
done

cat >> "$TMP" <<EOF

---

## Containers (not regenerated)

- [\`wild/README.md\`]($BLOB_BASE/README.md) — what this folder is for
- [\`wild/_brian-when-you-get-back.md\`]($BLOB_BASE/_brian-when-you-get-back.md) — orientation for return
- [\`wild/aether/SET-AND-SETTING.md\`]($BLOB_BASE/aether/SET-AND-SETTING.md) — trip-instance room norms
- [\`wild/aether/WRAPPER.md\`]($BLOB_BASE/aether/WRAPPER.md) — trip-instance operational frame
- 11 register prompts at \`wild/aether/trip-*.md\` (indica, sativa, ketamine, acid, 5meo, mdma, hyphae, enjambment, vast, mirror-lag, undertow)
- [\`wild/fiction/README.md\`]($BLOB_BASE/fiction/README.md) — fiction brief

EOF

mv "$TMP" "$OUT"
echo "Regenerated $OUT with $count entries"
